Update index.js
jonschlinkert/arr-diff pull request #6
Opened 2017-09-26 15:11 UTC by BlackHole1

The first parameter should be judged

2017-09-26 17:20 UTC, jonschlinkert requested changes

2017-09-26 17:20 UTC, jonschlinkert commented on index.js
> +      arr = [];
Please revert this and use the same formatting as the rest of the code.

2017-09-26 17:34 UTC, BlackHole1 commented
OK

2017-10-03 17:06 UTC, doowb commented on index.js
> +  var len = arguments.length,
This should be a `;` at the end of the line.

2018-10-23 15:40 UTC, doowb commented on index.js
> +  var len = arguments.length,
```suggestion
  var len = arguments.length;
```

2026-08-22 08:27 UTC, closed without merging